@baseUrl = http://localhost:3001

### HELLO / Bienvenida
GET {{baseUrl}}/

### LIBROS

### Listado de todos los libros
GET {{baseUrl}}/api/libros

### Obtener un libro específico (ID 2)
GET {{baseUrl}}/api/libros/2

### ---------------------REGISTRO---------------------------

### Registro -> 201
POST {{baseUrl}}/api/auth/registro
Content-Type: application/json

{ "nombre": "Ana", "email": "ana@libreria.test", "password": "Libreria2026" }

### Registro con el mismo mail -> 409
POST {{baseUrl}}/api/auth/registro
Content-Type: application/json

{ "nombre": "Ana", "email": "ana@libreria.test", "password": "Libreria2026" }

### Registro con datos inválidos → 400 
POST {{baseUrl}}/api/auth/registro
Content-Type: application/json

{ "nombre": "", "email": "no-es-1-mail", "password": "aaaj" }


### ---------------------LOGIN---------------------------

### Login con mail que no existe → 401 
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ "email": "nobody@libreria.test", "password": "Libreria2026" }

### Login con password incorrecta → 401
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ "email": "ana@libreria.test", "password": "incorrect4" }

### Login ← el @name es lo que permite capturar la respuesta -> 200
# @name login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ "email": "ana@libreria.test", "password": "Libreria2026" }

### Guardamos el token de la respuesta anterior
@token = {{login.response.body.token}}


### Login de ADMIN (del seed) → 200 
# @name loginAdmin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{ "email": "admin@libreria.test", "password": "Admin1234" }

### El token queda guardado
@tokenAdmin = {{loginAdmin.response.body.token}}


### ---------------------Rutas Protegidas---------------------------

### /auth/yo sin token -> 401
GET {{baseUrl}}/api/auth/yo

### /auth/yo con token de CLIENTE → 200
GET {{baseUrl}}/api/auth/yo
Authorization: Bearer {{token}}

### libro sin header → 401
POST {{baseUrl}}/api/libros
Content-Type: application/json

{ "titulo": "Rayuela", "precio": 7000, "imagen": "https://…", "autorId": 1 }

### Crear libro con token de Cliente → 403
POST {{baseUrl}}/api/libros
Content-Type: application/json
Authorization: Bearer {{token}}

{ "titulo": "Rayuela", "precio": 7000, "imagen": "https://…", "autorId": 1 }

### Crear libro con token de admin → 201
POST {{baseUrl}}/api/libros
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{ "titulo": "Rayuela", "precio": 7000, "imagen": "https://…", "autorId": 1 }


### admin con body inválido → 400
POST {{baseUrl}}/api/libros
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{ "precio": -5 }

### 13 · Borrar libro con token de CLIENTE → 403
DELETE {{baseUrl}}/api/libros/1
Authorization: Bearer {{token}}


### ──────────────---─ ROMPER EL TOKEN --- ───────────────

### Token con el payload modificado a mano → 401 
GET {{baseUrl}}/api/auth/yo
Authorization: Bearer kwrBFO2yDD2bcUw5vuQUTLFOenbjBpGToUrYlvwJ46Z1

### Token que no es un token → 401 
GET {{baseUrl}}/api/auth/yo
Authorization: Bearer this is not a token

### Header sin el prefijo Bearer → 401
GET {{baseUrl}}/api/auth/yo
Authorization: {{token}}



### Listado de solo los disponibles
GET {{baseUrl}}/api/libros?disponible=true

### Listado de solo los no disponibles
GET {{baseUrl}}/api/libros?disponible=false

### Crear un libro nuevo 
POST {{baseUrl}}/api/libros
Content-Type: application/json

{
  "titulo": "Ficciones",
  "autor": "Jorge Luis Borges",
  "precio": 4500,
  "imagen": "https://covers.openlibrary.org/b/id/10452332-L.jpg",
  "disponible": true
}

### Actualizar un libro
PUT {{baseUrl}}/api/libros/1
Content-Type: application/json

{
  "titulo": "Cien años de soledad (Edición Ilustrada)",
  "autor": "Gabriel García Márquez",
  "precio": 38000,
  "imagen": "https://covers.openlibrary.org/b/id/10452332-L.jpg",
  "disponible": true
}

### Borrar un libro 
DELETE {{baseUrl}}/api/libros/3

## AUTORES

### Listado de autores
GET {{baseUrl}}/api/autores

### Obtener un autor específico 
GET {{baseUrl}}/api/autores/2

### Crear un autor
POST {{baseUrl}}/api/autores
Content-Type: application/json

{
  "nombre": "Jorge Luis Borges",
  "nacionalidad": "Argentina",
  "nacimiento": 1899
}

### Actualizar un autor 
PUT {{baseUrl}}/api/autores/1
Content-Type: application/json

{
  "nombre": "Gabo García Márquez",
  "nacionalidad": "Colombiana",
  "nacimiento": 1927
}

### Borrar un autor 
DELETE {{baseUrl}}/api/autores/2


### Error 400 - crear un libro sin título
POST {{baseUrl}}/api/libros
Content-Type: application/json

{ "precio": 5000, "imagen": "https://…", "autorId": 1 }

### Error 400 - libro con id inválido
GET {{baseUrl}}/api/libros/abc

### Error 400 - el autor no existe (formato válido, dato imposible)
POST {{baseUrl}}/api/libros
Content-Type: application/json

{ "titulo": "Huérfano", "precio": 5000, "imagen": "https://…", "autorId": 9999 }

### Rrror 409 - crear un autor duplicado
POST {{baseUrl}}/api/autores

{ "nombre": "Gabriel García Márquez", "nacionalidad": "Colombia", "nacimiento": 1927 }

### Error 409 - borrar un autor con libros (onDelete: Restrict)
DELETE {{baseUrl}}/api/autores/1

### Error 404 - actualizar algo que no existe
PUT {{baseUrl}}/api/libros/9999
